CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE CORRELATIVOS(
	IDCORRE VARCHAR(5) PRIMARY KEY,
	ULTIMO INT,
	DETALLE VARCHAR(200)
);

CREATE TABLE PAISES(
	IDPAIS VARCHAR(9) PRIMARY KEY,
	PAIS VARCHAR(150) NOT NULL
);

CREATE TABLE AUTORES(
	IDAUTOR VARCHAR(9) PRIMARY KEY,
	AUTOR VARCHAR(150) NOT NULL,
	IDPAIS VARCHAR(9) NOT NULL,
	FOREIGN KEY (IDPAIS) REFERENCES PAISES (IDPAIS)
);

CREATE TABLE GENEROS_LITERARIOS(
	IDGENL VARCHAR(9) PRIMARY KEY,
	GENEROLIT VARCHAR(150) NOT NULL
);

CREATE TABLE EDITORIALES(
	IDEDIT VARCHAR(9) PRIMARY KEY NOT NULL,
	EDITORIAL VARCHAR(150) NOT NULL,
	DIREDIT VARCHAR(150) DEFAULT 'N/A',
	TELEDIT VARCHAR(10) DEFAULT 'N/A',
	EMAILEDIT VARCHAR(150) DEFAULT 'N/A'
);

CREATE TABLE LIBROS(
	IDLIBRO VARCHAR(9) PRIMARY KEY NOT NULL,
	LIBRO VARCHAR(100) NOT NULL,
	DESCLIBRO VARCHAR(150) NOT NULL,
	IDAUTOR VARCHAR(9) NOT NULL,
	IDGENL VARCHAR(9) NOT NULL,
	IDEDIT VARCHAR(9) NOT NULL,
	EDITION VARCHAR(50) NOT NULL,
	APULIB VARCHAR(10) NOT NULL,
	ISBN VARCHAR(50),
	STOCK INT NOT NULL,
	FOREIGN KEY (IDAUTOR) REFERENCES AUTORES (IDAUTOR),
	FOREIGN KEY (IDGENL) REFERENCES GENEROS_LITERARIOS (IDGENL),
	FOREIGN KEY (IDEDIT) REFERENCES EDITORIALES (IDEDIT)
);

CREATE DATABASE EMPLEADOS(
	IDEMP VARCHAR(9) PRIMARY KEY NOT NULL,
	DOCEMP VARCHAR(20) NOT NULL,
	NOMEMP VARCHAR(150) NOT NULL,
	APEEMP VARCHAR(150) NOT NULL,
	DIREMP VARCHAR(150) NOT NULL,
	EMAILEMP VARCHAR(150) NOT NULL,
	SEXO VARCHAR(50) NOT NULL,
	TELEMP VARCHAR(10) NOT NULL,
	FNACEMP DATE(SHORT) NOT NULL,
	CARGOEMP VARCHAR(150) NOT NULL,
	SALARIOEMP DECIMAL(10,2) NOT NULL
);

--Tablas Adicionales
CREATE TABLE FACULTADES(
	IDFAC VARCHAR(9) PRIMARY KEY NOT NULL,
	FACULTAD VARCHAR(150) NOT NULL
);

CREATE TABLE MOTIVOS_VISITA(
	IDMOTV VARCHAR(9) PRIMARY KEY NOT NULL,
	MOTV VARCHAR(100) NOT NULL
);

SELECT * FROM GENEROS_LITERARIOS;
SELECT * FROM PAISES;