Use BIBLIOTECA;

--CORRELATVOS
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('AUT', 0, 'CORRELATIVO DE AUTORES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('CTY', 0, 'CORRELATIVO DE PAISES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('GNL', 0, 'CORRELATIVO DE GENEROS LITERARIOS');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('EDT', 0, 'CORRELATIVO DE EDITORIALES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('LIB', 0, 'CORRELATIVO DE LIBROS');

--PAISES
INSERT INTO PAISES (IDPAIS, PAIS) VALUES ('CTY000073', 'Haití');
INSERT INTO PAISES (IDPAIS, PAIS) VALUES ('CTY000074', 'Honduras');

--AUTORES
INSERT INTO AUTORES (IDAUTOR, AUTOR, IDPAIS) VALUES ('AUT000001', 'JUAN PINEDA', 'CTY000073');
INSERT INTO AUTORES (IDAUTOR, AUTOR, IDPAIS) VALUES ('AUT000002', 'MARIA ESCOBAR', 'CTY000074');

--GENEROS_LITERARIOS
INSERT INTO GENEROS_LITERARIOS (IDGENL, GENEROLIT) VALUES ('GNL000001', 'NARRATIVO');
INSERT INTO GENEROS_LITERARIOS (IDGENL, GENEROLIT) VALUES ('GNL000002', 'LIRICO');

--EDITORIALES
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00001', 'Editorial Iberoamericana', 'Calle Street al lado de el edificio x', '2662-0812', 'editorialiberoamericana@gmail.com');
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00002', 'Editorial Guaymuras', 'Calle Street al lado de el edificio y', '2662-0872', 'editorialguaymuras@gmail.com');
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00003', 'Editorial Ramón Amaya Amador', 'Calle Street al lado de el edificio z', '2662-0092', 'editorialraa@gmail.com');

SELECT * FROM LIBROS;