Use BIBLIOTECA;

--CORRELATVOS
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('AUT', 2, 'CORRELATIVO DE AUTORES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('CTY', 2, 'CORRELATIVO DE PAISES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('GNL', 2, 'CORRELATIVO DE GENEROS LITERARIOS');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('EDT', 2, 'CORRELATIVO DE EDITORIALES');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('LIB', 0, 'CORRELATIVO DE LIBROS');
INSERT INTO CORRELATIVOS (IDCORRE, ULTIMO, DETALLE) VALUES ('EMP', 2, 'CORRELATIVO DE EMPLEADOS');

--PAISES
INSERT INTO PAISES (IDPAIS, PAIS) VALUES ('CTY000073', 'Haití');
INSERT INTO PAISES (IDPAIS, PAIS) VALUES ('CTY000074', 'Honduras');

--AUTORES
INSERT INTO AUTORES (IDAUTOR, AUTOR, IDPAIS) VALUES ('AUT000001', 'JUAN PINEDA', 'CTY000073');
INSERT INTO AUTORES (IDAUTOR, AUTOR, IDPAIS) VALUES ('AUT000002', 'MARIA ESCOBAR', 'CTY000074');

--GENEROS_LITERARIOS
INSERT INTO GENEROS_LITERARIOS (IDGENL, GENEROLIT) VALUES ('GNL000001', 'NARRATIVO');
INSERT INTO GENEROS_LITERARIOS (IDGENL, GENEROLIT) VALUES ('GNL000002', 'LIRICO');

--EDITORIALES
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00001', 'Editorial Iberoamericana', 'Calle Street al lado de el edificio x', '2662-0812', 'editorialiberoamericana@gmail.com');
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00002', 'Editorial Guaymuras', 'Calle Street al lado de el edificio y', '2662-0872', 'editorialguaymuras@gmail.com');
INSERT INTO EDITORIALES (IDEDIT, EDITORIAL, DIREDIT, TELEDIT, EMAILEDIT) 
VALUES ('EDT00003', 'Editorial Ramón Amaya Amador', 'Calle Street al lado de el edificio z', '2662-0092', 'editorialraa@gmail.com');

INSERT INTO EMPLEADOS (IDEMP, DOCEMP, NOMEMP, APEEMP, DIREMP, EMAILEMP, SEXO, TELEMP, FNACEMP, CARGOEMP, SALARIOEMP)
VALUES ('EMP000001','0408-1990-14785','PEDRO', 'PEREZ','CALLE PRINCIPAL 456, COLONIA KENNEDY, TEGUCIGALPA, HONDURAS','PEDRITOPERES23@GMAIL.COM','MASCULINO','7894-4561','1990-08-14','GERENTE',15000.50);
INSERT INTO EMPLEADOS (IDEMP, DOCEMP, NOMEMP, APEEMP, DIREMP, EMAILEMP, SEXO, TELEMP, FNACEMP, CARGOEMP, SALARIOEMP)
VALUES ('EMP000002','0111-1989-10085','LAURA', 'FLORES','AVENIDA LA PAZ 789, BARRIO EL CENTRO, SAN PEDRO SULA, HONDURAS','LAURAFLORES13@GMAIL.COM','FEMENINO','8080-4991','1989-01-25','ASISTENTE',12000.00);
INSERT INTO EMPLEADOS (IDEMP, DOCEMP, NOMEMP, APEEMP, DIREMP, EMAILEMP, SEXO, TELEMP, FNACEMP, CARGOEMP, SALARIOEMP)
VALUES ('EMP000003','1511-1995-00100','FELIPE', 'MARTINEZ','CALLE REAL 123, COLONIA SAN CARLOS, LA CEIBA, HONDURAS', 'FELIPE07@GMAIL.COM','FEMENINO','9741-5123','1995-07-15','REGISTRO',13000.00);


SELECT * FROM LIBROS;